import assert from 'node:assert/strict'
import { readFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'

const root = new URL('..', import.meta.url)
const read = (path) => readFileSync(new URL(path, root), 'utf8')

const app = read('src/App.tsx')
const appCSS = read('src/App.css')
const commandSurface = read('src/ui/command-surface/PPTSurfaceCommands.tsx')
const commandSurfaceModel = read('src/ui/command-surface/PPTSurfaceCommandModel.ts')
const controls = read('src/ui/core/controls.tsx')
const controlsCSS = read('src/ui/core/controls.css')
const editorChrome = read('src/ui/core/useEditorChrome.ts')
const editorShell = read('src/ui/shell/EditorShell.tsx')
const inspectorActionDispatcher = read('src/ui/inspector/PPTInspectorActionDispatcher.ts')
const commentInspectorFields = read('src/ui/inspector/PPTCommentInspectorFields.tsx')
const commentThreadAdapter = read('src/pptCommentThreadAdapter.ts')
const imageInspectorFields = read('src/ui/inspector/PPTImageInspectorFields.tsx')
const imageAdapter = read('src/pptImageAdapter.ts')
const inspectorRoot = read('src/ui/inspector/PPTInspector.tsx')
const selectionInspectorPanel = read('src/ui/inspector/PPTSelectionInspectorPanel.tsx')
const lineInspectorFields = read('src/ui/inspector/PPTLineInspectorFields.tsx')
const lineAdapter = read('src/pptLineAdapter.ts')
const tableInspectorFields = read('src/ui/inspector/PPTTableInspectorFields.tsx')
const tableAdapter = read('src/pptTableAdapter.ts')
const objectPropertiesInspectorFields = read('src/ui/inspector/PPTObjectPropertiesInspectorFields.tsx')
const shapeInspectorFields = read('src/ui/inspector/PPTShapeInspectorFields.tsx')
const objectAdapter = read('src/pptObjectAdapter.ts')
const objectAnimationInspectorFields = read('src/ui/inspector/PPTObjectAnimationInspectorFields.tsx')
const objectAnimationAdapter = read('src/pptObjectAnimationAdapter.ts')
const colorSwatchStrip = read('src/ui/inspector/PPTColorSwatchStrip.tsx')
const colorSwatchAdapter = read('src/pptColorSwatchAdapter.ts')
const textInspectorFields = read('src/ui/inspector/PPTTextInspectorFields.tsx')
const textAdapter = read('src/pptTextAdapter.ts')
const inspectorContract = read('src/ui/inspector/PPTInspectorContract.ts')
const inspectorCSS = read('src/ui/inspector/inspector.css')
const inspectorIndex = read('src/ui/inspector/index.ts')
const inspectorShell = read('src/ui/inspector/PPTInspectorShell.tsx')
const layerPane = read('src/ui/inspector/PPTLayerPane.tsx')
const layerPaneAdapter = read('src/pptLayerPaneAdapter.ts')
const slideInspectorPanel = read('src/ui/inspector/PPTSlideInspectorPanel.tsx')
const indexCSS = read('src/index.css')
const packageJSON = read('package.json')
const alignmentPopover = read('src/ui/selection-toolbar/PPTAlignmentPopover.tsx')
const paragraphAlign = read('src/ui/text-formatting/PPTParagraphAlignRadioGroup.tsx')
const selectionToolbar = read('src/ui/selection-toolbar/PPTSelectionToolbar.tsx')
const selectionToolbarCSS = read('src/ui/selection-toolbar/selection-toolbar.css')
const shellCSS = read('src/ui/shell/editor-shell.css')
const shapeKindMenu = read('src/ui/selection-toolbar/PPTShapeKindMenu.tsx')
const textFormattingCSS = read('src/ui/text-formatting/text-formatting.css')
const textQuickFormat = read('src/ui/selection-toolbar/PPTTextQuickFormatControls.tsx')
const tokensCSS = read('src/ui/core/tokens.css')
const viteConfig = read('vite.config.ts')

const expectedImports = [
  "@import './ui/core/tokens.css';",
  "@import './ui/core/controls.css';",
  "@import './ui/shell/editor-shell.css';",
]

assert.deepEqual(
  appCSS.split('\n').slice(0, expectedImports.length),
  expectedImports,
  'App.css must load UI tokens, primitives, and shell styles in that order',
)

for (const token of [
  '--ppt-ui-control-size',
  '--ppt-ui-control-size-compact',
  '--ppt-ui-control-gap',
  '--ppt-ui-radius-md',
  '--ppt-ui-shadow-floating',
  '--ppt-ui-z-selection-toolbar',
  '--ppt-ui-z-toolbar',
]) {
  assert.match(tokensCSS, new RegExp(token), `Missing UI token: ${token}`)
}

assert.match(controls, /label: string/, 'IconButton must require an accessible label')
assert.match(controlsCSS, /\.ppt-icon-button/, 'Control styles must own icon buttons')
assert.doesNotMatch(appCSS, /^\.ppt-icon-button\s*[,\{]/m, 'App.css must not redefine core icon buttons')
assert.doesNotMatch(appCSS, /^\.ppt-floating-command\s*[,\{]/m, 'App.css must not redefine floating controls')
assert.doesNotMatch(appCSS, /\.ppt-topbar\s*\{/, 'App.css must not redefine the editor shell')
assert.match(shellCSS, /\.ppt-topbar\s*\{/, 'Shell styles must own the editor toolbar')
assert.match(app, /<EditorShell/, 'PPT must compose its root through the editor shell seam')
assert.match(app, /<EditorToolbar/, 'PPT must compose its toolbar through the editor shell seam')
const inspectorCall = app.match(/<PPTInspector[\s\S]*?\/>/)?.[0] ?? ''
assert.match(inspectorCall, /model=\{\{/, 'App must pass one cohesive Inspector model')
assert.match(inspectorCall, /onAction=\{handleInspectorAction\}/, 'App must translate one Inspector action stream')
assert.doesNotMatch(inspectorCall, /on(?:Comment|Commit|Copy|Color|Download|Element|Image|Layer|Layout|Line|Object|Paragraph|Shape|Slide|Table|Text)[A-Z]/, 'App must not regress to field-level Inspector callbacks')
assert.match(inspectorRoot, /function PPTInspector\(\{ model, onAction \}: PPTInspectorProps\)/, 'PPT Inspector must consume its model and action contract')
assert.match(app, /function handleInspectorAction\(action: PPTInspectorAction\)/, 'App must own Inspector action translation')
assert.match(inspectorContract, /type PPTInspectorProps = \{[\s\S]*model: PPTInspectorModel[\s\S]*onAction: \(action: PPTInspectorAction\) => void[\s\S]*\}/, 'Inspector must expose one model and one action interface')
assert.match(inspectorContract, /type PPTInspectorAction =[\s\S]*type: 'set-slide-transition'/, 'Inspector action contract must cover slide and selection editing')
assert.match(inspectorActionDispatcher, /function createPPTInspectorActionDispatcher/, 'Inspector dispatcher must own field event to action translation')
assert.doesNotMatch(inspectorContract, /function createPPTInspectorActionDispatcher/, 'Inspector contract must remain a pure type surface')
assert.doesNotMatch(app, /function onElement(?:Geometry|TextStyle|Shadow)Change/, 'App must not own Inspector field event adapters')
assert.match(inspectorRoot, /<PPTInspectorShell[\s\S]*model=\{model\}[\s\S]*onAction=\{onAction\}[\s\S]*selectionPanel=\{[\s\S]*<PPTSelectionInspectorPanel model=\{model\} onAction=\{onAction\} \/>/, 'PPT Inspector must compose its UI through the Inspector Shell and Selection panel seams')
assert.doesNotMatch(app, /PPTInspectorShell|PPTSelectionInspectorPanel|PPT[A-Za-z]+InspectorFields|createPPTInspectorActionDispatcher/, 'App must depend only on the public Inspector root and action contract')
assert.match(selectionInspectorPanel, /function PPTSelectionInspectorPanel\([\s\S]*}: PPTInspectorProps\)/, 'Selection Inspector panel must consume the Inspector model and action contract')
assert.match(selectionInspectorPanel, /if \(!model\.selectedElement\)[\s\S]*className="ppt-muted">None</, 'Selection Inspector panel must own the empty selection state')
assert.doesNotMatch(app, /PPT_INSPECTOR_TABS|data-ppt-inspector-tabs|advancedInspectorOpen|createPPTCanvasTabsDescriptor/, 'App must not own Inspector shell state or tab behavior')
assert.match(inspectorShell, /data-ppt-inspector-tabpanel="slide"[\s\S]*<PPTSlideInspectorPanel model=\{model\} onAction=\{onAction\} \/>/, 'Inspector Shell must compose the Slide panel through its model and action seam')
assert.match(inspectorShell, /createPPTCanvasTabsDescriptor/, 'Inspector Shell must reuse the Canvas tabs descriptor')
assert.match(inspectorShell, /getPPTCanvasTabsKeyboardIntent/, 'Inspector Shell must reuse the Canvas tabs keyboard affordance')
assert.match(inspectorShell, /previousInspectorSelectionStateRef/, 'Inspector Shell must own selection-driven tab activation')
assert.match(inspectorShell, /data-ppt-inspector-advanced-toggle/, 'Inspector Shell must own advanced property disclosure')
assert.match(inspectorShell, /className="ppt-export-code"/, 'Inspector Shell must own the advanced export surface')
assert.match(selectionInspectorPanel, /<PPTCommentInspectorFields model=\{model\} onAction=\{onAction\} \/>/, 'Selection Inspector must compose Comment fields through the Inspector action seam')
assert.doesNotMatch(app, /commentReplyDraftById|className="ppt-comment-thread"|function (?:update|commit)CommentReplyDraft/, 'App must not own Comment Inspector state or rendering')
assert.match(commentInspectorFields, /type PPTCommentInspectorFieldsProps = Pick<[\s\S]*'model' \| 'onAction'/, 'Comment Inspector fields must expose only the Inspector model and action seam')
assert.match(commentInspectorFields, /createPPTInspectorActionDispatcher\(onAction\)/, 'Comment Inspector fields must translate interactions through the Inspector action dispatcher')
assert.match(commentInspectorFields, /useState<Record<string, string>>/, 'Comment Inspector fields must own reply draft state')
assert.match(commentThreadAdapter, /export function normalizePPTCommentReplyBody/, 'Comment adapter must own reply normalization')
assert.match(commentThreadAdapter, /export function getPPTCommentThread/, 'Comment adapter must own fallback thread projection')
assert.doesNotMatch(app, /function normalizePPTCommentReplyBody|function getPPTCommentThread\(/, 'App must consume the Comment adapter rather than reimplement it')
assert.match(selectionInspectorPanel, /<PPTImageInspectorFields model=\{model\} onAction=\{onAction\} \/>/, 'Selection Inspector must compose Image fields through the Inspector action seam')
assert.doesNotMatch(app, /imageReplaceInputRef|data-ppt-image-replace-action|data-ppt-style-field="image-fit"/, 'App must not own Image Inspector state or rendering')
assert.match(imageInspectorFields, /type PPTImageInspectorFieldsProps = Pick<[\s\S]*'model' \| 'onAction'/, 'Image Inspector fields must expose only the Inspector model and action seam')
assert.match(imageInspectorFields, /createPPTInspectorActionDispatcher\(onAction\)/, 'Image Inspector fields must translate interactions through the Inspector action dispatcher')
assert.match(imageInspectorFields, /useRef<HTMLInputElement \| null>/, 'Image Inspector fields must own the replace file input ref')
assert.match(imageInspectorFields, /getPPTImageCropDescriptor\(model\.slide\.id, image\)/, 'Image Inspector fields must consume the PPT image descriptor adapter')
assert.match(imageAdapter, /export function getPPTImageFit/, 'Image adapter must own fit defaults')
assert.match(imageAdapter, /export function getPPTImageCrop/, 'Image adapter must own crop defaults')
assert.match(imageAdapter, /export function getPPTImageCropDescriptor/, 'Image adapter must own crop descriptor projection')
assert.match(imageAdapter, /export function getPPTImageReplaceDescriptor/, 'Image adapter must own replace descriptor projection')
assert.doesNotMatch(app, /function (?:getPPTImageFit|getPPTImageCrop|getPPTImageCropDescriptor|getPPTImageReplaceDescriptor|isPPTImageFit)\(/, 'App must consume the Image adapter rather than reimplement it')
assert.match(selectionInspectorPanel, /<PPTObjectPropertiesInspectorFields model=\{model\} onAction=\{onAction\} \/>/, 'Selection Inspector must compose Object Properties through the Inspector action seam')
assert.doesNotMatch(app, /data-ppt-style-field="(?:name|opacity|hyperlink|alt-text)"|data-ppt-shadow-inspector|data-ppt-geometry-field/, 'App must not own Object Properties Inspector rendering')
assert.match(objectPropertiesInspectorFields, /type PPTObjectPropertiesInspectorFieldsProps = Pick<[\s\S]*'model' \| 'onAction'/, 'Object Properties fields must expose only the Inspector model and action seam')
assert.match(objectPropertiesInspectorFields, /createPPTInspectorActionDispatcher\(onAction\)/, 'Object Properties fields must translate interactions through the Inspector action dispatcher')
assert.match(objectPropertiesInspectorFields, /getPPTObjectOpacityDescriptor\(/, 'Object Properties fields must consume the PPT object descriptor adapter')
assert.match(objectPropertiesInspectorFields, /getPPTObjectShadowDescriptor\(/, 'Object Properties fields must consume the PPT shadow descriptor adapter')
assert.doesNotMatch(objectPropertiesInspectorFields, /pptSlideEditAffordanceAdapter/, 'Object Properties UI must depend on the PPT object boundary rather than Canvas package details')
assert.match(objectAdapter, /export function getPPTObjectOpacityDescriptor/, 'Object adapter must own opacity descriptor projection')
assert.match(objectAdapter, /export function getPPTObjectHyperlinkDescriptor/, 'Object adapter must own hyperlink descriptor projection')
assert.match(objectAdapter, /export function getPPTObjectAccessibilityDescriptor/, 'Object adapter must own accessibility descriptor projection')
assert.match(objectAdapter, /export function getPPTObjectShadowDescriptor/, 'Object adapter must own shadow descriptor projection')
assert.match(objectAdapter, /export function normalizePPTElementShadow/, 'Object adapter must own shadow normalization')
assert.doesNotMatch(app, /function (?:getPPTElementOpacity|getPPTObjectOpacityDescriptor|getPPTElementHyperlink|getPPTObjectHyperlinkDescriptor|getPPTElementAltText|getPPTObjectAccessibilityDescriptor|getPPTElementShadow|getPPTObjectShadowDescriptor|normalizePPTElementShadow)\(/, 'App must consume the Object adapter rather than reimplement it')
assert.match(selectionInspectorPanel, /<PPTShapeInspectorFields model=\{model\} onAction=\{onAction\} \/>/, 'Selection Inspector must compose Shape fields through the Inspector action seam')
assert.doesNotMatch(app, /data-ppt-style-field="(?:shape|shape-corner-radius|fill|fill-opacity|stroke-color|stroke-width|stroke-dash)"|data-ppt-color-control="shape-(?:fill|stroke)"/, 'App must not own Shape Inspector rendering')
assert.match(shapeInspectorFields, /type PPTShapeInspectorFieldsProps = Pick<[\s\S]*'model' \| 'onAction'/, 'Shape Inspector fields must expose only the Inspector model and action seam')
assert.match(shapeInspectorFields, /createPPTInspectorActionDispatcher\(onAction\)/, 'Shape Inspector fields must translate interactions through the Inspector action dispatcher')
assert.match(shapeInspectorFields, /<PPTColorSwatchStrip[\s\S]*model=\{model\}[\s\S]*onAction=\{onAction\}/, 'Shape Inspector fields must compose shared color swatches through the Inspector seam')
assert.match(shapeInspectorFields, /getPPTCornerRadiusDescriptor\(/, 'Shape Inspector fields must consume the PPT corner radius descriptor adapter')
assert.match(shapeInspectorFields, /getPPTFillOpacityDescriptor\(/, 'Shape Inspector fields must consume the PPT fill descriptor adapter')
assert.match(shapeInspectorFields, /getPPTStrokeLineStyleDescriptor\(/, 'Shape Inspector fields must consume the PPT stroke descriptor adapter')
assert.doesNotMatch(shapeInspectorFields, /pptSlideEditAffordanceAdapter/, 'Shape Inspector UI must depend on the PPT object boundary rather than Canvas package details')
assert.match(objectAdapter, /export function getPPTCornerRadiusDescriptor/, 'Object adapter must own corner radius descriptor projection')
assert.match(objectAdapter, /export function getPPTFillOpacityDescriptor/, 'Object adapter must own fill opacity descriptor projection')
assert.match(objectAdapter, /export function getPPTStrokeLineStyleDescriptor/, 'Object adapter must own stroke line style descriptor projection')
assert.match(objectAdapter, /export function normalizePPTFill/, 'Object adapter must own fill normalization')
assert.match(objectAdapter, /export function normalizePPTStroke/, 'Object adapter must own stroke normalization')
assert.match(objectAdapter, /export function getPPTFillColorCSS/, 'Object adapter must own fill CSS projection')
assert.match(objectAdapter, /export function getPPTElementBorderStyle/, 'Object adapter must own object border CSS projection')
assert.doesNotMatch(app, /function (?:getPPTCornerRadiusDescriptor|getPPTFillOpacityDescriptor|getPPTStrokeLineStyleDescriptor|normalizePPTFill|normalizePPTStroke|getPPTFillColorCSS|getPPTElementBorderStyle)\(/, 'App must consume the Object style adapter rather than reimplement it')
assert.match(selectionInspectorPanel, /<PPTLineInspectorFields model=\{model\} onAction=\{onAction\} \/>/, 'Selection Inspector must compose Line fields through the Inspector action seam')
assert.doesNotMatch(app, /data-ppt-style-field="(?:line-stroke-color|line-stroke-width|line-stroke-dash|line-route|line-start-marker|line-end-marker)"|data-ppt-color-control="line-stroke"/, 'App must not own Line Inspector rendering')
assert.match(lineInspectorFields, /type PPTLineInspectorFieldsProps = Pick<[\s\S]*'model' \| 'onAction'/, 'Line Inspector fields must expose only the Inspector model and action seam')
assert.match(lineInspectorFields, /createPPTInspectorActionDispatcher\(onAction\)/, 'Line Inspector fields must translate interactions through the Inspector action dispatcher')
assert.match(lineInspectorFields, /<PPTColorSwatchStrip[\s\S]*model=\{model\}[\s\S]*onAction=\{onAction\}/, 'Line Inspector fields must compose shared color swatches through the Inspector seam')
assert.match(lineInspectorFields, /getPPTStrokeLineStyleDescriptor\(/, 'Line Inspector fields must consume the shared PPT stroke descriptor adapter')
assert.doesNotMatch(lineInspectorFields, /pptSlideEditAffordanceAdapter/, 'Line Inspector UI must depend on PPT line and object boundaries rather than Canvas package details')
assert.match(lineAdapter, /export function getPPTLineRoute/, 'Line adapter must own route defaults')
assert.match(lineAdapter, /export function getPPTLineMarker/, 'Line adapter must own marker defaults')
assert.match(lineAdapter, /export function isPPTLineRoute/, 'Line adapter must own route validation')
assert.match(lineAdapter, /export function isPPTLineMarker/, 'Line adapter must own marker validation')
assert.doesNotMatch(app, /function isPPT(?:LineRoute|LineMarker)\(/, 'App must consume the Line adapter rather than reimplement line validation')
assert.match(selectionInspectorPanel, /<PPTTableInspectorFields model=\{model\} onAction=\{onAction\} \/>/, 'Selection Inspector must compose Table fields through the Inspector action seam')
assert.doesNotMatch(app, /data-ppt-style-field="table-data"|data-ppt-table-inspector-size/, 'App must not own Table Inspector rendering')
assert.match(tableInspectorFields, /type PPTTableInspectorFieldsProps = Pick<[\s\S]*'model' \| 'onAction'/, 'Table Inspector fields must expose only the Inspector model and action seam')
assert.match(tableInspectorFields, /createPPTInspectorActionDispatcher\(onAction\)/, 'Table Inspector fields must translate interactions through the Inspector action dispatcher')
assert.match(tableInspectorFields, /getPPTTableInspectorModel\(element\)/, 'Table Inspector fields must consume one cohesive PPT table read model')
assert.doesNotMatch(tableInspectorFields, /pptImportExtension|pptSlideEditAffordanceAdapter/, 'Table Inspector UI must not depend on import or Canvas package details')
assert.match(tableAdapter, /export function getPPTTableInspectorModel/, 'Table adapter must own Inspector read model projection')
assert.match(selectionInspectorPanel, /<PPTObjectAnimationInspectorFields model=\{model\} onAction=\{onAction\} \/>/, 'Selection Inspector must compose Object Animation through the Inspector action seam')
assert.doesNotMatch(app, /data-ppt-object-animation-inspector|data-ppt-animation-field=/, 'App must not own Object Animation Inspector rendering')
assert.match(objectAnimationInspectorFields, /type PPTObjectAnimationInspectorFieldsProps = Pick<[\s\S]*'model' \| 'onAction'/, 'Object Animation fields must expose only the Inspector model and action seam')
assert.match(objectAnimationInspectorFields, /createPPTInspectorActionDispatcher\(onAction\)/, 'Object Animation fields must translate interactions through the Inspector action dispatcher')
assert.match(objectAnimationInspectorFields, /getPPTObjectAnimationDescriptor\(/, 'Object Animation fields must consume the PPT animation descriptor adapter')
assert.match(objectAnimationInspectorFields, /data-ppt-animation-trigger-options=\{PPT_OBJECT_ANIMATION_PACKAGE_TRIGGERS\.join\(' '\)\}/, 'Object Animation diagnostics must expose Canvas package trigger ids')
assert.match(objectAnimationInspectorFields, /data-ppt-animation-type-options=\{PPT_OBJECT_ANIMATION_PACKAGE_TYPES\.join\(' '\)\}/, 'Object Animation diagnostics must expose Canvas package type ids')
assert.doesNotMatch(objectAnimationInspectorFields, /pptSlideEditAffordanceAdapter/, 'Object Animation UI must depend on the PPT animation boundary rather than Canvas package details')
assert.match(objectAnimationAdapter, /export function normalizePPTElementAnimation/, 'Object Animation adapter must own animation normalization')
assert.match(objectAnimationAdapter, /export function getPPTObjectAnimationDescriptor/, 'Object Animation adapter must own descriptor projection')
assert.match(objectAnimationAdapter, /export function getPPTSlideAnimationBuildOrder/, 'Object Animation adapter must own build order projection')
assert.match(objectAnimationAdapter, /export function toSlideEditObjectAnimationCommand/, 'Object Animation adapter must own Canvas command translation')
assert.match(objectAnimationAdapter, /export function getPPTElementAnimationTypeFromJSONValue/, 'Object Animation adapter must own JSON value parsing')
assert.match(objectAnimationAdapter, /PPT_OBJECT_ANIMATION_PACKAGE_TRIGGERS[\s\S]*SLIDE_EDIT_OBJECT_ANIMATION_TRIGGERS\.map/, 'Object Animation adapter must project Canvas package trigger ids')
assert.match(objectAnimationAdapter, /PPT_OBJECT_ANIMATION_PACKAGE_TYPES[\s\S]*SLIDE_EDIT_OBJECT_ANIMATION_TYPES\.map/, 'Object Animation adapter must project Canvas package type ids')
assert.doesNotMatch(app, /function (?:getPPTElementAnimation|normalizePPTElementAnimation|getPPTObjectAnimationDescriptor|getPPTSlideAnimationBuildOrder|toSlideEditObjectAnimationCommand|toPPTElementAnimationUpdate|getPPTElementAnimationStyle|getPPTElementAnimationTypeFromJSONValue)\(/, 'App must consume the Object Animation adapter rather than reimplement it')
assert.doesNotMatch(app, /PPTColorSwatchStrip|function getPPTColorSwatchDescriptor\(/, 'App must not own color swatch UI or descriptor projection')
assert.match(colorSwatchStrip, /type PPTColorSwatchStripProps = Pick<[\s\S]*'model' \| 'onAction'[\s\S]*target: PPTColorSwatchTarget/, 'Color Swatch Strip must expose the Inspector seam and one cohesive target')
assert.match(colorSwatchStrip, /createPPTInspectorActionDispatcher\(onAction\)/, 'Color Swatch Strip must translate selection through the Inspector action dispatcher')
assert.doesNotMatch(colorSwatchStrip, /onSelect:|pptSlideEditAffordanceAdapter/, 'Color Swatch Strip must not expose callback props or Canvas package details')
assert.match(colorSwatchAdapter, /export type PPTColorSwatchTarget = \{[\s\S]*channel:[\s\S]*color:[\s\S]*elementId:/, 'Color Swatch adapter must own the cohesive color target contract')
assert.match(colorSwatchAdapter, /export function getPPTColorSwatchPackageChannel/, 'Color Swatch adapter must own PPT to Canvas channel mapping')
assert.match(colorSwatchAdapter, /export function getPPTColorSwatchDescriptor/, 'Color Swatch adapter must own palette descriptor projection')
assert.match(inspectorContract, /type PPTInspectorColorSwatchChannel = PPTColorSwatchChannel/, 'Inspector must reuse the PPT color channel contract')
assert.match(selectionInspectorPanel, /<PPTTextInspectorFields model=\{model\} onAction=\{onAction\} \/>/, 'Selection Inspector must compose Text fields through the Inspector action seam')
assert.doesNotMatch(app, /data-ppt-(?:text-inset-inspector|paragraph-spacing-inspector|text-overflow-inspector)|data-ppt-style-field="(?:text|text-color|font-size|font-family|vertical-align|font-weight)"/, 'App must not own Text Inspector rendering')
assert.match(textInspectorFields, /type PPTTextInspectorFieldsProps = Pick<[\s\S]*'model' \| 'onAction'/, 'Text Inspector fields must expose only the Inspector model and action seam')
assert.match(textInspectorFields, /createPPTInspectorActionDispatcher\(onAction\)/, 'Text Inspector fields must translate interactions through the Inspector action dispatcher')
assert.match(textInspectorFields, /<PPTColorSwatchStrip[\s\S]*model=\{model\}[\s\S]*onAction=\{onAction\}/, 'Text Inspector fields must compose shared color swatches through the Inspector seam')
assert.match(textInspectorFields, /getPPTTextParagraphSpacingDescriptor\(/, 'Text Inspector fields must consume the PPT paragraph descriptor adapter')
assert.match(textInspectorFields, /getPPTTextFontFamilyDescriptor\(/, 'Text Inspector fields must consume the PPT font descriptor adapter')
assert.match(textInspectorFields, /getPPTTextVerticalAlignmentDescriptor\(/, 'Text Inspector fields must consume the PPT vertical alignment descriptor adapter')
assert.match(textInspectorFields, /getPPTTextFrameInsetDescriptor\(/, 'Text Inspector fields must consume the PPT text inset descriptor adapter')
assert.doesNotMatch(textInspectorFields, /pptSlideEditAffordanceAdapter/, 'Text Inspector UI must depend on the PPT text boundary rather than Canvas package details')
assert.match(textAdapter, /export function getPPTTextParagraphSpacingDescriptor/, 'Text adapter must own paragraph spacing descriptor projection')
assert.match(textAdapter, /export function toSlideEditParagraphSpacingCommand/, 'Text adapter must own paragraph spacing command translation')
assert.match(textAdapter, /export function getPPTTextFontFamilyDescriptor/, 'Text adapter must own font descriptor projection')
assert.match(textAdapter, /export function getPPTTextVerticalAlignmentDescriptor/, 'Text adapter must own vertical alignment descriptor projection')
assert.match(textAdapter, /export function getPPTTextFrameInsetDescriptor/, 'Text adapter must own text inset descriptor projection')
assert.match(textAdapter, /export function getPPTTextAutoFitSizeMode/, 'Text adapter must own autofit size mode projection')
assert.doesNotMatch(app, /function (?:getPPTTextParagraphSpacingDescriptor|toSlideEditParagraphSpacingCommand|getPPTTextFontFamilyDescriptor|getPPTTextVerticalAlignmentDescriptor|getPPTTextFrameInsetDescriptor|getPPTTextAutoFitSizeMode)\(/, 'App must consume the Text adapter rather than reimplement it')
assert.match(inspectorContract, /type PPTInspectorParagraphSpacingField = PPTParagraphSpacingField/, 'Inspector must reuse the PPT paragraph spacing field contract')
assert.match(inspectorContract, /type PPTInspectorTextInsetField = PPTTextInsetField/, 'Inspector must reuse the PPT text inset field contract')
assert.doesNotMatch(app, /data-ppt-slide-field="(?:name|background|layout|notes)"/, 'App must not own Slide inspector fields')
assert.doesNotMatch(app, /onSlide(?:Name|Background|Layout|Notes|Transition)Change/, 'App must not own Slide inspector field event adapters')
assert.match(slideInspectorPanel, /type PPTSlideInspectorPanelProps = Pick<[\s\S]*'model' \| 'onAction'/, 'Slide Inspector panel must expose only the Inspector model and action seam')
assert.match(slideInspectorPanel, /createPPTInspectorActionDispatcher\(onAction\)/, 'Slide Inspector panel must translate controls through the Inspector action dispatcher')
assert.match(slideInspectorPanel, /createSlideEditTransitionDescriptor/, 'Slide Inspector panel must reuse the Canvas-selected transition affordance')
assert.match(slideInspectorPanel, /data-ppt-slide-metadata-field/, 'Slide Inspector panel must own slide metadata field rendering')
assert.match(inspectorShell, /<PPTLayerPane model=\{model\} onAction=\{onAction\} \/>/, 'Inspector Shell must compose the Layer Pane through its model and action seam')
assert.doesNotMatch(app, /data-ppt-layer-pane(?:=|\s*\n)/, 'App must not own Layer Pane rendering')
assert.doesNotMatch(app, /function (?:runLayerPaneIntent|handleLayerPaneRow|startLayerPaneRename)/, 'App must not own Layer Pane interactions')
assert.doesNotMatch(app, /layerPaneGroupState|layerPaneRenameState|layerPaneDragState/, 'App must not own Layer Pane local state')
assert.match(layerPane, /type PPTLayerPaneProps = Pick<PPTInspectorProps, 'model' \| 'onAction'>/, 'Layer Pane must expose only the Inspector model and action seam')
assert.match(layerPane, /createPPTInspectorActionDispatcher\(onAction\)/, 'Layer Pane must translate interactions through the Inspector action dispatcher')
assert.match(layerPane, /getSlideEditLayerPaneKeyboardIntent/, 'Layer Pane must reuse the Canvas-selected keyboard affordance')
assert.match(layerPane, /getSlideEditLayerPaneDropIndicator/, 'Layer Pane must reuse the Canvas-selected drag affordance')
assert.match(layerPane, /getPPTCanvasSelectionListModifierState/, 'Layer Pane must reuse the Canvas selection modifier affordance')
assert.match(layerPaneAdapter, /export function createPPTLayerPaneDescriptor/, 'Layer Pane adapter must own PPT row projection')
assert.match(layerPaneAdapter, /export function getPPTLayerPaneSelection/, 'Layer Pane adapter must own PPT selection translation')
assert.match(layerPaneAdapter, /export function reorderPPTLayerPaneElement/, 'Layer Pane adapter must own PPT reorder translation')
assert.match(inspectorIndex, /import '\.\/inspector\.css'/, 'Inspector public module must load its co-located styles')
assert.match(inspectorIndex, /export \{ PPTInspector \} from '\.\/PPTInspector'/, 'Inspector public module must expose the cohesive Inspector root')
assert.doesNotMatch(inspectorIndex, /PPT(?:ColorSwatch|Comment|Image|Layer|Line|Object|Selection|Shape|Slide|Table|Text)|createPPTInspectorActionDispatcher/, 'Inspector public module must not expose internal panels, fields, or dispatchers')
for (const selector of [
  '.ppt-panel-section',
  '.ppt-field',
  '.ppt-slide-transition-fields',
  '.ppt-layer-list',
  '.ppt-export-code',
]) {
  const escapedSelector = selector.replace('.', '\\.')
  assert.match(inspectorCSS, new RegExp(`^${escapedSelector}(?:\\s|,|\\{)`, 'm'), `Inspector styles must own ${selector}`)
  assert.doesNotMatch(appCSS, new RegExp(`^${escapedSelector}(?:\\s|,|\\{)`, 'm'), `App.css must not own ${selector}`)
}
assert.match(app, /<PPTSelectionToolbar[\s\S]*model=\{\{[\s\S]*onAction=\{handleSelectionToolbarAction\}/, 'App must cross the selection toolbar seam through model and action')
assert.doesNotMatch(app, /<PPTAlignmentPopover(?:\s|\/)|<PPTShapeKindMenu(?:\s|\/)|<PPTTextQuickFormatControls(?:\s|\/)/, 'App must not compose selection toolbar internals')
assert.doesNotMatch(app, /function PPTSelectionFloatingBar|function PPTTextQuickFormatControls|function PPTParagraphAlignRadioGroup/, 'App must not own selection toolbar or text control implementation')
assert.doesNotMatch(app, /function PPTAlignmentPopover/, 'App must not own alignment menu implementation')
assert.doesNotMatch(app, /function PPTShapeKindMenu/, 'App must not own shape menu implementation')
assert.doesNotMatch(app, /PPT_ALIGNMENT_POPOVER_COMMANDS|PPT_SHAPE_MENU_OPTIONS|PPT_COMMAND_SURFACE_GROUPS/, 'App must not own UI command registries')
assert.match(app, /useEditorChrome/, 'PPT must use the shared editor chrome module')
assert.doesNotMatch(app, /useExclusiveDisclosure/, 'PPT must not compose chrome from a shallow disclosure hook')
assert.doesNotMatch(app, /setToolShelfOpen|setViewOptionsOpen|setExportOptionsOpen|setShowGrid|setShowFrameGuides|setShowMinimap|setInspectorOpen/, 'Editor chrome must not drift back to independent booleans')
assert.doesNotMatch(app, /className="ppt-(?:button|floating-command|icon-button|slide-action)"/, 'App controls must use UI core primitives')
assert.match(editorChrome, /useReducer/, 'Editor chrome policy must be centralized in one reducer')
assert.match(editorChrome, /activeTransientSurface: null/, 'Transient editor chrome must start closed')
assert.match(editorChrome, /inspectorOpen: false/, 'Inspector must start closed')
assert.match(editorChrome, /frameGuides: false[\s\S]*grid: false[\s\S]*minimap: false/, 'Secondary view features must start hidden')
assert.match(editorChrome, /event\.key === 'Escape'/, 'Escape must dismiss transient editor chrome')
assert.match(editorShell, /data-editor-inspector-open/, 'Editor shell must own inspector layout state')
assert.match(editorShell, /data-editor-transient-surface/, 'Editor toolbar must expose one transient surface state')
assert.match(shellCSS, /data-editor-inspector-open/, 'Shell CSS must consume the generic inspector state')
assert.match(shellCSS, /data-editor-transient-surface/, 'Shell CSS must consume the generic transient surface state')
assert.match(shellCSS, /\.ppt-app\s*\{[^}]*position: relative/, 'Editor shell must establish the mobile Inspector containing block')
assert.match(shellCSS, /@media \(max-width: 920px\)[\s\S]*?\.ppt-inspector\s*\{[^}]*position: absolute/, 'Mobile Inspector must overlay the editor inside its shell')
assert.doesNotMatch(shellCSS, /data-ppt-(?:inspector-open|tool-shelf-open|view-options-open|export-options-open)/, 'Shell layout must not depend on PPT diagnostic state')
assert.match(selectionToolbar, /type PPTSelectionToolbarProps = \{[\s\S]*model: PPTSelectionToolbarModel[\s\S]*onAction: \(action: PPTSelectionToolbarAction\) => void[\s\S]*\}/, 'Selection toolbar must expose one model and one action interface')
assert.match(selectionToolbar, /<PPTAlignmentPopover/, 'Selection toolbar must compose the alignment popover')
assert.match(selectionToolbar, /<PPTShapeKindMenu/, 'Selection toolbar must compose the shape menu')
assert.match(selectionToolbar, /<PPTTextQuickFormatControls/, 'Selection toolbar must compose quick text formatting')
assert.doesNotMatch(selectionToolbar, /onTextBoldToggle|onTextItalicToggle|onFontSizeStep|onParagraphAlign/, 'Selection toolbar must not regress to callback-per-control')
assert.match(selectionToolbar, /import '\.\/selection-toolbar\.css'/, 'Selection toolbar must load its co-located styles')
assert.match(selectionToolbarCSS, /\.ppt-selection-floating-bar\s*\{/, 'Selection toolbar styles must own the floating bar')
assert.doesNotMatch(appCSS, /\.ppt-selection-floating-bar\s*\{/, 'App.css must not own selection toolbar styles')
assert.match(commandSurfaceModel, /const COMMAND_GROUPS:/, 'Command surface model must own the command registry')
assert.match(commandSurfaceModel, /export function getPPTCommandSurfaceGroups/, 'Command surface model must derive surface-specific command views')
assert.match(commandSurface, /export function PPTSurfaceCommandButton/, 'Command surface must own command rendering')
assert.doesNotMatch(app, /function PPTSurfaceCommandButton|function getPPTCommandSurfaceGroups/, 'App must consume the command surface module')
assert.match(textQuickFormat, /onAction: \(action: PPTTextQuickFormatAction\) => void/, 'Quick text formatting must emit one action stream')
assert.match(paragraphAlign, /PPT_RADIO_GROUP_FOCUS_MODEL/, 'Paragraph alignment must own its Canvas focus affordance')
assert.match(paragraphAlign, /handlePPTCanvasRadioGroupKeyDown/, 'Paragraph alignment must own keyboard behavior')
assert.match(textFormattingCSS, /grid-template-columns: repeat\(4, minmax\(0, 1fr\)\)/, 'Paragraph alignment must reserve one stable column per option')
assert.doesNotMatch(appCSS, /\.ppt-segmented-control\s*\{/, 'App.css must not own shared text formatting controls')
assert.match(alignmentPopover, /availability: Readonly<Record<PPTAlignmentPopoverCommand, boolean>>/, 'Alignment menu must receive availability through its public interface')
assert.match(alignmentPopover, /onPreviewChange: \(command: PPTAlignmentPopoverCommand \| null\) => void/, 'Alignment menu must own preview lifecycle behind one callback')
assert.match(shapeKindMenu, /state: PPTShapeQuickMenuState/, 'Shape menu must receive a cohesive state value')

for (const [name, source] of [
  ['alignment popover', alignmentPopover],
  ['shape kind menu', shapeKindMenu],
]) {
  assert.match(source, /usePPTCanvasMenuRovingFocus/, `${name} must own roving menu focus`)
  assert.match(source, /focusPPTCanvasElementOnNextFrame/, `${name} must restore trigger focus`)
  assert.match(source, /getPPTCanvasMenuTriggerKeyboardIntent/, `${name} must reuse the Canvas menu trigger affordance`)
}

for (const [name, source] of [
  ['package.json', packageJSON],
  ['src/index.css', indexCSS],
  ['vite.config.ts', viteConfig],
]) {
  assert.doesNotMatch(source, /tailwind/i, `${name} must not introduce a second styling system`)
}

const coreDirectory = new URL('src/ui/core/', root)
for (const fileName of readdirSync(coreDirectory)) {
  if (!/\.(ts|tsx)$/.test(fileName)) {
    continue
  }

  const source = readFileSync(join(coreDirectory.pathname, fileName), 'utf8')
  assert.doesNotMatch(
    source,
    /from ['"](?:\.\.\/){2}|from ['"].*(?:ppt|canvas)/i,
    `UI core must not depend on PPT or canvas implementation: ${fileName}`,
  )
}

console.log('UI core structure verified')
