import {
  PPTDeckSchema,
  PPT_SLIDE_HEIGHT,
  PPT_SLIDE_WIDTH,
  createPPTTextBody,
  type PPTDeck,
} from './pptModel'

export const SAMPLE_PPT_DECK: PPTDeck = PPTDeckSchema.parse({
  id: 'deck-ai-retouch',
  size: {
    h: PPT_SLIDE_HEIGHT,
    w: PPT_SLIDE_WIDTH,
  },
  slides: [
    {
      background: { color: '#f8fafc' },
      elements: [
        {
          geometry: { h: 108, w: 760, x: 84, y: 78 },
          id: 's1-title',
          kind: 'textBox',
          name: 'Title',
          style: { color: '#111827', fontSize: 56, fontWeight: 'bold' },
          textBody: createPPTTextBody('AI pitch deck draft'),
        },
        {
          geometry: { h: 84, w: 670, x: 88, y: 208 },
          id: 's1-summary',
          kind: 'textBox',
          name: 'Summary',
          style: { color: '#475569', fontSize: 25 },
          textBody: createPPTTextBody(
            'A lightweight deck editor for AI-generated slides and last-mile edits.',
          ),
        },
        {
          fill: { color: '#e0f2fe' },
          geometry: { h: 226, w: 330, x: 88, y: 378 },
          id: 's1-card-1',
          kind: 'shape',
          name: 'Card 1',
          shape: 'rect',
          stroke: { color: '#0ea5e9', width: 2 },
          style: { color: '#0f172a', fontSize: 28, fontWeight: 'semibold' },
          textBody: createPPTTextBody('Fast draft\nSmall edits'),
        },
        {
          fill: { color: '#dcfce7' },
          geometry: { h: 226, w: 330, x: 474, y: 378 },
          id: 's1-card-2',
          kind: 'shape',
          name: 'Card 2',
          shape: 'rect',
          stroke: { color: '#22c55e', width: 2 },
          style: { color: '#14532d', fontSize: 28, fontWeight: 'semibold' },
          textBody: createPPTTextBody('PPT subset\nCanvas tools'),
        },
        {
          fill: { color: '#fff7ed' },
          geometry: { h: 470, w: 300, x: 902, y: 112 },
          id: 's1-side-panel',
          kind: 'shape',
          name: 'Side Panel',
          shape: 'rect',
          stroke: { color: '#fb923c', width: 2 },
          style: { color: '#7c2d12', fontSize: 24, fontWeight: 'semibold' },
          textBody: createPPTTextBody('Generated\nthen retouched'),
        },
      ],
      id: 'slide-1',
      name: 'Overview',
      notes: 'Tighten the title and adjust the cards after AI generation.',
    },
    {
      background: { color: '#ffffff' },
      elements: [
        {
          geometry: { h: 78, w: 780, x: 84, y: 78 },
          id: 's2-title',
          kind: 'textBox',
          name: 'Title',
          style: { color: '#111827', fontSize: 46, fontWeight: 'bold' },
          textBody: createPPTTextBody('Minimal subset now, PPTX later'),
        },
        {
          fill: { color: '#eff6ff' },
          geometry: { h: 154, w: 1010, x: 92, y: 208 },
          id: 's2-strip-1',
          kind: 'shape',
          name: 'Strip 1',
          shape: 'rect',
          stroke: { color: '#60a5fa', width: 2 },
          style: { color: '#1e3a8a', fontSize: 24, fontWeight: 'semibold' },
          textBody: createPPTTextBody('PPTDeck keeps slide, element, geometry, and textBody structure.'),
        },
        {
          fill: { color: '#f0fdf4' },
          geometry: { h: 154, w: 1010, x: 92, y: 408 },
          id: 's2-strip-2',
          kind: 'shape',
          name: 'Strip 2',
          shape: 'rect',
          stroke: { color: '#4ade80', width: 2 },
          style: { color: '#14532d', fontSize: 24, fontWeight: 'semibold' },
          textBody: createPPTTextBody('Canvas package tools handle selection, transform, resize, and snap.'),
        },
      ],
      id: 'slide-2',
      name: 'Model',
      notes: '',
    },
  ],
  title: 'AI Retouch Demo',
})

