import type { RetouchSlide } from './retouchModel'

export const SAMPLE_DECK_SECONDARY_SLIDES: RetouchSlide[] = [
  {
    id: 'slide-4',
    name: 'Problem',
    accent: '#c2410c',
    blocks: [
      {
        id: 's4-title',
        role: 'title',
        tag: 'h1',
        text: 'Why this exists',
        className: 'block-title compact centered',
        x: 300,
        y: 92,
        width: 680,
        height: 78,
      },
      {
        id: 's4-quote',
        role: 'body',
        tag: 'div',
        text: 'AI can draft a deck quickly, but small last-mile edits are where trust breaks.',
        className: 'block-quote centered',
        x: 230,
        y: 210,
        width: 820,
        height: 116,
      },
      {
        id: 's4-card-1',
        role: 'metric',
        tag: 'div',
        text: 'Regenerate\nFast, but unpredictable',
        className: 'block-mini centered',
        x: 246,
        y: 410,
        width: 300,
        height: 104,
      },
      {
        id: 's4-card-2',
        role: 'metric',
        tag: 'div',
        text: 'Manual CSS\nPrecise, but too slow',
        className: 'block-mini secondary centered',
        x: 734,
        y: 410,
        width: 300,
        height: 104,
      },
      {
        id: 's4-note',
        role: 'note',
        tag: 'p',
        text: 'The product targets the narrow moment after generation, before final delivery.',
        className: 'block-note slim centered',
        x: 260,
        y: 584,
        width: 760,
        height: 76,
      },
    ],
  },
  {
    id: 'slide-5',
    name: 'System',
    accent: '#7c3aed',
    blocks: [
      {
        id: 's5-title',
        role: 'title',
        tag: 'h1',
        text: 'System model',
        className: 'block-title compact centered',
        x: 300,
        y: 104,
        width: 680,
        height: 78,
      },
      {
        id: 's5-step-1',
        role: 'card',
        tag: 'div',
        text: 'Source\nHTML/CSS blocks',
        className: 'block-step centered',
        x: 168,
        y: 282,
        width: 260,
        height: 150,
      },
      {
        id: 's5-step-2',
        role: 'card',
        tag: 'div',
        text: 'Patch\nText + layout ops',
        className: 'block-step strong centered',
        x: 510,
        y: 282,
        width: 260,
        height: 150,
      },
      {
        id: 's5-step-3',
        role: 'card',
        tag: 'div',
        text: 'Export\nMerged final HTML',
        className: 'block-step centered',
        x: 852,
        y: 282,
        width: 260,
        height: 150,
      },
      {
        id: 's5-footer',
        role: 'body',
        tag: 'p',
        text: 'Original slide code stays intact; every edit is explicit and undoable.',
        className: 'block-footer centered',
        x: 300,
        y: 548,
        width: 680,
        height: 62,
      },
    ],
  },
  {
    id: 'slide-6',
    name: 'Quality',
    accent: '#0891b2',
    blocks: [
      {
        id: 's6-title',
        role: 'title',
        tag: 'h1',
        text: 'Quality gate',
        className: 'block-title wide centered',
        x: 320,
        y: 104,
        width: 640,
        height: 78,
      },
      {
        id: 's6-quote',
        role: 'body',
        tag: 'div',
        text: 'Text changes should not move layout. Layout changes should not rewrite text.',
        className: 'block-quote centered',
        x: 240,
        y: 244,
        width: 800,
        height: 120,
      },
      {
        id: 's6-card-1',
        role: 'metric',
        tag: 'div',
        text: 'Regression\nKorean input\nmulti-select move',
        className: 'block-mini centered',
        x: 312,
        y: 432,
        width: 260,
        height: 112,
      },
      {
        id: 's6-card-2',
        role: 'metric',
        tag: 'div',
        text: 'Checks\nlint\nbuild\nMVP script',
        className: 'block-mini secondary centered',
        x: 708,
        y: 432,
        width: 260,
        height: 112,
      },
      {
        id: 's6-note',
        role: 'note',
        tag: 'p',
        text: 'The demo stays small so interaction quality is visible, not buried under features.',
        className: 'block-note slim centered',
        x: 260,
        y: 584,
        width: 760,
        height: 76,
      },
    ],
  },
]
