import type { RetouchDeck } from './retouchModel'
import { SAMPLE_DECK_SECONDARY_SLIDES } from './sampleDeckSecondarySlides'

export const SAMPLE_DECK: RetouchDeck = {
  slides: [
    {
      id: 'slide-1',
      name: 'Overview',
      accent: '#2563eb',
      blocks: [
        {
          id: 's1-title',
          role: 'title',
          tag: 'h1',
          text: 'PPT Retouch',
          className: 'block-title centered',
          x: 240,
          y: 158,
          width: 800,
          height: 84,
        },
        {
          id: 's1-subtitle',
          role: 'subtitle',
          tag: 'p',
          text: 'A final-touch editor for AI-generated HTML/CSS slides.',
          className: 'block-subtitle centered',
          x: 280,
          y: 284,
          width: 720,
          height: 86,
        },
        {
          id: 's1-metric',
          role: 'metric',
          tag: 'div',
          text: 'Core bet\nText / Layout separation',
          className: 'block-metric centered',
          x: 500,
          y: 418,
          width: 280,
          height: 112,
        },
        {
          id: 's1-note',
          role: 'note',
          tag: 'div',
          text: 'Goal: edit copy and layout without exposing CSS numbers.',
          className: 'block-note centered',
          x: 280,
          y: 572,
          width: 720,
          height: 76,
        },
      ],
    },
    {
      id: 'slide-2',
      name: 'Agenda',
      accent: '#0f766e',
      blocks: [
        {
          id: 's2-title',
          role: 'title',
          tag: 'h1',
          text: 'Workflow',
          className: 'block-title compact centered',
          x: 300,
          y: 104,
          width: 680,
          height: 78,
        },
        {
          id: 's2-step-1',
          role: 'card',
          tag: 'div',
          text: '1\nText Mode\nEdit copy only',
          className: 'block-step centered',
          x: 168,
          y: 284,
          width: 260,
          height: 150,
        },
        {
          id: 's2-step-2',
          role: 'card',
          tag: 'div',
          text: '2\nLayout Mode\nSelect, move, resize',
          className: 'block-step strong centered',
          x: 510,
          y: 284,
          width: 260,
          height: 150,
        },
        {
          id: 's2-step-3',
          role: 'card',
          tag: 'div',
          text: '3\nExport\nHTML/CSS + patch',
          className: 'block-step centered',
          x: 852,
          y: 284,
          width: 260,
          height: 150,
        },
        {
          id: 's2-footer',
          role: 'body',
          tag: 'p',
          text: 'The surface stays small so the current operation is obvious.',
          className: 'block-footer centered',
          x: 300,
          y: 548,
          width: 680,
          height: 62,
        },
      ],
    },
    {
      id: 'slide-3',
      name: 'Decision',
      accent: '#4f46e5',
      blocks: [
        {
          id: 's3-title',
          role: 'title',
          tag: 'h1',
          text: 'MVP Standard',
          className: 'block-title wide centered',
          x: 320,
          y: 118,
          width: 640,
          height: 78,
        },
        {
          id: 's3-quote',
          role: 'body',
          tag: 'div',
          text: 'Make final retouching simpler and less risky than regenerating.',
          className: 'block-quote centered',
          x: 240,
          y: 260,
          width: 800,
          height: 130,
        },
        {
          id: 's3-card-1',
          role: 'metric',
          tag: 'div',
          text: 'Allowed\nText edits\nDrag / resize',
          className: 'block-mini centered',
          x: 312,
          y: 452,
          width: 260,
          height: 96,
        },
        {
          id: 's3-card-2',
          role: 'metric',
          tag: 'div',
          text: 'Excluded\nLLM hookup\nCSS editor',
          className: 'block-mini secondary centered',
          x: 708,
          y: 452,
          width: 260,
          height: 96,
        },
        {
          id: 's3-note',
          role: 'note',
          tag: 'p',
          text: 'Checks: title edit, body shortening, card movement, export parity.',
          className: 'block-note slim centered',
          x: 260,
          y: 584,
          width: 760,
          height: 76,
        },
      ],
    },
    ...SAMPLE_DECK_SECONDARY_SLIDES,
  ],
}

export const SAMPLE_SLIDES = SAMPLE_DECK.slides
